In [12]:
import numpy as np

array = np.array ([0,1,2,3,4,5,6,7,8,9])

print (array)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
import numpy as np

even = np.arange (10)

print (even)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
bool_arr = np.ones((3,3), dtype=bool)
print(bool_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [27]:
import numpy as np
a = np.arange(11)

print(a)

a[a % 2 == 1]

[ 0  1  2  3  4  5  6  7  8  9 10]


array([1, 3, 5, 7, 9])

In [32]:
import numpy as np

a = np.arange(11)

print (a)

a[a % 2 == 1] = -1

print (a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


In [39]:
import numpy as np 

array = np.array([1,2,3,4,5,6,7,8,9,10])

print (array)

newArray = array.reshape(2,5)

print(newArray)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [47]:
import numpy as np

a = np.arange (1,17).reshape (4,4)  
b = np.arange (19,35).reshape (4,4)  
c = np.dot(a,b)

sum = np.sum (c)

print(c)
print (sum)

[[ 270  280  290  300]
 [ 670  696  722  748]
 [1070 1112 1154 1196]
 [1470 1528 1586 1644]]
14736
